# Features to use
USE_PUPIL_FEATURES = True
USE_DISTANCE_FEATURES = True
USE_FIXATION_PATH_FEATURES = True
USE_PUPIL_AOI_FEATURES = True
USE_DISTANCE_AOI_FEATURES = True
USE_FIXATION_AOI_FEATURES = True
USE_TRANSITION_AOI_FEATURES = True

# Sets of features to keep
KEEP_TASK_FEATURES = True
KEEP_GLOBAL_FEATURES = True

#Frequency of ML/EMDAT calls:
EMDAT_CALL_PERIOD = 7000
ML_CALL_PERIOD = 6000000
